// Hand-written, and NOT regenerated by `pnpm gen:types` (`worker-configuration.d.ts` is).
//
// ANTHROPIC_API_KEY is a Workers Secret (BYOK) — it has no `vars` entry in
// wrangler.jsonc (secrets never do), so `wrangler types` can only discover
// it by reading a local `.dev.vars` file. That file is gitignored and
// absent on a clean checkout or in CI, so `wrangler types` silently omits
// ANTHROPIC_API_KEY from the generated `Env` there — proven by running
// `pnpm gen:types` on a checkout with no `.dev.vars` (review round 1,
// finding 6). Any later ticket that adds a binding and re-runs `gen:types`
// would silently lose this field and break `env.ANTHROPIC_API_KEY` typing
// for no visible reason.
//
// Declaring it here instead — via TypeScript's declaration merging with
// the generated `Env` / `Cloudflare.Env` interfaces — makes the type
// reproducible from the repo alone, independent of local `.dev.vars`
// state. `scripts/verify-types-reproducible.mjs` (run by `pnpm check`)
// asserts `wrangler types` no longer needs to touch this field, so this
// file is the single place it can drift from reality.
interface Env {
  ANTHROPIC_API_KEY: string;
}

declare namespace Cloudflare {
  interface Env {
    ANTHROPIC_API_KEY: string;
  }
}
